services:

  postgres:
    image: postgres:17-alpine
    container_name: vakurra_bot_db

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5434:5432"

    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: ..
      dockerfile: infra/docker/dev/Dockerfile

    container_name: vakurra_bot

    restart: unless-stopped

    env_file:
      - ../.env

    working_dir: /app

    volumes:
      - ../:/app

    command: sh -c "alembic -c infra/alembic.ini upgrade head && watchfiles 'python -m backend.bot.main'"

    depends_on:
      postgres:
        condition: service_healthy

  api:
    build:
      context: ..
      dockerfile: infra/docker/dev/Dockerfile

    container_name: vakurra_api

    restart: unless-stopped

    env_file:
      - ../.env

    working_dir: /app

    volumes:
      - ../:/app

    command: watchfiles "uvicorn backend.api.main:app --host 0.0.0.0 --port 8000"

    ports:
      - "8001:8000"

    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ..
      dockerfile: infra/docker/frontend/dev.Dockerfile

    container_name: vakurra_frontend_dev

    working_dir: /app
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules

    command: npm run dev

    ports:
      - "5173:5173"

    depends_on:
      - api

volumes:
  postgres_data_dev:
  frontend_node_modules:
