"""add rejection reason

Revision ID: 94647b34b3bf
Revises: 3c51113f99b1
Create Date: 2026-10-04 11:19:31.183801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94647b34b3bf'
down_revision: Union[str, Sequence[str], None] = '3c51113f99b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_bots', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_bots', 'rejection_reason')
    # ### end Alembic commands ###
